---
bibliography: references.bib
---

# Instalación y configuración de entorno

Este apartado describe el proceso para descargar e instalar las herramientas de trabajo para realizar práticas de programamción en lenguaje R.

Lenguaje R

R es un lenguaje y entorno para gráficos y computación estadística. Es de código abierto o libre de la comunidad y movimiento de software libre GNU.

R proporciona una amplia variedad de técnicas estadísticas (modelado lineal y no lineal, pruebas estadísticas clásicas, análisis de series de tiempo, clasificación, agrupamiento,...) y técnicas gráficas, y es altamente extensible.

Una de las fortalezas de R es la facilidad con la que se pueden producir gráficos con calidad de publicación bien diseñados, incluidos símbolos matemáticos y fórmulas cuando sea necesario.

R es utilizado normalmente en contexto de investigación y docencia sin, embargo. existe una visión de su aplicación y uso en el ámbito empresarial.

R está disponible como Software Libre bajo los términos de la Licencia Pública General GNU de la Free Software Foundation en forma de código fuente [@r.fundation2021a]

Se puede [descargar R de servidor itam.mx](https://cran.itam.mx/ "Descrgar R de servidor itam.mx") de entre varios servidores o espejos (mirrors) disponibles para su descarga y elegir la distribución conforme y de acuerdo a las características de su equipo.

![Descargar R [@r.fundation2021]](images/descargar%20R.jpg "descargar R")

Ahora bien

Descargar R

Instalar R

R Studio

Descarar R Studio

Instalar R Studio
